#!/bin/bash

#read the file
if [ -n "$1" ] ; then
    FILE="$1"
else
    echo -n "Enter file name: "
    read FILE
fi

#read the list of ips from the file and run the scan
while read line; do
    echo  "running scan for: ${line}"
    nmap -sV --version-all $line >> "${FILE}.result" 
done < $FILE

